sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
addons:
  apt:
    sources:
      - git-core
    packages:
      - git
before_script:
  - git fetch --unshallow origin refs/heads/master:refs/remotes/origin/master
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+(\\-.*)?$/"
